### ISSUE TITLE
error getting recent oplog entry: mongo: no documents in result

### ISSUE THREAD

**Issue by dolisss** [tuladhar/k8s-backup-mongodb#1]
I tried this approach on one cluster and it worked great, but when I do the same on another, I am facing this error:

_[backup-mongodb] Dumping all MongoDB databases to compressed archive...
2021-04-05T10:19:33.311+0000    writing admin.system.version to archive 'mongodump_20210405_101933.gz'
2021-04-05T10:19:33.314+0000    done dumping admin.system.version (1 document)
2021-04-05T10:19:33.315+0000    Failed: error getting oplog start: error getting recent oplog entry: mongo: no documents in result_

I checked this in the MongoDB document but couldn't find something that can help me. can you relate anything to this error?
Thanks in advance!

**Comment by tuladhar** [comment]
Thanks @dolisss. I haven't encountered this issue. Please check if replication is healthy on another cluster, this might be helpful: https://docs.mongodb.com/manual/reference/method/db.getReplicationInfo/

**Comment by Sean2525** [comment]
@dolisss Is your another mongodb using standalone architecture?
I got this bug in a standalone cluster, so I added the command to remove --oplog option.
Now it works fine.
```
              command:
                - /bin/sh
                - -c
                - sed -i "s/^\(mongodump\).*/\1 \\\/g" backup-mongodb.sh; ./backup-mongodb.sh
```

**Comment by dolisss** [comment]
@Sean2525 Yah, I removed the command too, and then it worked!!
Later on, build an image for the standalone instance with --oplog removed.

**Comment by tuladhar** [comment]
Thanks @Sean2525. I'm glad the workaround worked for you @dolisss. The use-case I had was taking dump from  MongoDB replica set, so `--oplog` only works against nodes that maintain an oplog which includes all members of a replica set.

**Reference:**
* https://docs.mongodb.com/database-tools/mongodump/#std-option-mongodump.--oplog

**Comment by tuladhar** [comment]
@Sean2525 @dolisss I've added a feature to enable/disable oplog flag based on `MONGODB_OPLOG` environment variable passed in K8s cronjob.
